In [1]:
Pkg.checkout("MyMatchingA")

INFO: Checking out MyMatchingA master...
INFO: Pulling MyMatchingA latest master...
INFO: No packages to install, update or remove


In [2]:
Pkg.test("MyMatchingA")

INFO: Testing MyMatchingA


q = resp_rankings = [2 1 5; 3 2 5; 1 3 1; 4 4 5]
i = get_single(prop_matches) = 1
j = (prop_prefs[i])[prop_next_to_propose[i]] = 1
p = resp_matches[indptr[j]:indptr[j + 1] - 1] = [0]
a = findfirst(p,0) = 1
prop_next_to_propose[i] += 1 = 2
i = get_single(prop_matches) = 2
j = (prop_prefs[i])[prop_next_to_propose[i]] = 3
p = resp_matches[indptr[j]:indptr[j + 1] - 1] = [0]
i = get_single(prop_matches) = 2
one-to-one: Vector of Vectors: Error During Test
  Got an exception of type BoundsError outside of a @test
  BoundsError
   in getindex at ./number.jl:21 [inlined]
   in macro expansion at ./show.jl:218 [inlined]
   in deferred_acceptance(::Array{Int64,2}, ::Array{Int64,2}, ::Array{Int64,1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:99
   in deferred_acceptance(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:49
   in macro expansion; at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runte

ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 2 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:498
 in macro expansion; at ./test.jl:681 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runtests.jl, in expression starting on line 17
=============================[ ERROR: MyMatchingA ]=============================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --col

LoadError: MyMatchingA had test errors

In [3]:
using MyMatchingA

In [4]:
methods(deferred_acceptance)

# 4 methods for generic function "deferred_acceptance":
deferred_acceptance(prop_prefs::Array{Int64,2}, resp_prefs::Array{Int64,2}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:158
deferred_acceptance(prop_prefs::Array{Int64,2}, resp_prefs::Array{Int64,2}, caps::Array{Int64,1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:56
deferred_acceptance(m_prefs::Array{Array{Int64,1},1}, f_prefs::Array{Array{Int64,1},1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:30
deferred_acceptance(m_prefs::Array{Array{Int64,1},1}, f_prefs::Array{Array{Int64,1},1}, caps::Array{Int64,1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:5

In [3]:
methods(MyMatchingA.deferred_acceptance)

# 3 methods for generic function "deferred_acceptance":
deferred_acceptance(prop_prefs::Array{Int64,2}, resp_prefs::Array{Int64,2}, caps::Array{Int64,1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:56
deferred_acceptance(m_prefs::Array{Array{Int64,1},1}, f_prefs::Array{Array{Int64,1},1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:30
deferred_acceptance(m_prefs::Array{Array{Int64,1},1}, f_prefs::Array{Array{Int64,1},1}, caps::Array{Int64,1}) at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/src/MyMatchingA.jl:5

In [11]:
prop_prefs = [3  1  3  1;
              1  2  2  2;
              2  3  1  3;
              0  0  0  0]

4×4 Array{Int64,2}:
 3  1  3  1
 1  2  2  2
 2  3  1  3
 0  0  0  0

In [12]:
transpose(prop_prefs)

4×4 Array{Int64,2}:
 3  1  2  0
 1  2  3  0
 3  2  1  0
 1  2  3  0

In [3]:
prop_prefs=Array{Int}[[3,1,2,0],[1,2,3,0],[3,2,1,0],[1,2,3,0]]

4-element Array{Array{Int64,N},1}:
 [3,1,2,0]
 [1,2,3,0]
 [3,2,1,0]
 [1,2,3,0]

In [3]:
prop_prefs = [3 1 2 ;
              1 2 3 ;
              3 2 1 ;
              1 2 3 ]

4×3 Array{Int64,2}:
 3  1  2
 1  2  3
 3  2  1
 1  2  3

In [5]:
resp_prefs = [4  4  4;
              1  1  2;
              3  2  1;
              2  3  3;
              0  0  0]

5×3 Array{Int64,2}:
 4  4  4
 1  1  2
 3  2  1
 2  3  3
 0  0  0

In [12]:
resp_prefs = Array{Int}[[4,1,3,2,0],[4,1,2,3,0],[4,2,1,3,0]]

3-element Array{Array{Int64,N},1}:
 [4,1,3,2,0]
 [4,1,2,3,0]
 [4,2,1,3,0]

In [4]:
resp_prefs = [4 1 3 2 ;
              4 1 2 3 ;
              4 2 1 3 ]

3×4 Array{Int64,2}:
 4  1  3  2
 4  1  2  3
 4  2  1  3

In [9]:
size(resp_prefs, 1)

3

In [5]:
caps = [2,3,2]

3-element Array{Int64,1}:
 2
 3
 2

In [1]:
s_prefs = [
        5, 1, 0, 2, 3, 4,
        2, 5, 1, 0, 3, 4,
        3, 1, 0, 2, 4, 5,
        4, 1, 0, 2, 3, 5,
        1, 2, 0, 3, 4, 5,
        1, 3, 0, 2, 4, 5,
        1, 3, 4, 0, 2, 6,
    ]

42-element Array{Int64,1}:
 5
 1
 0
 2
 3
 4
 2
 5
 1
 0
 3
 4
 3
 ⋮
 1
 3
 0
 2
 4
 5
 1
 3
 4
 0
 2
 6

In [4]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [3]:
mat2vecs(s_prefs)

LoadError: MethodError: no method matching mat2vecs(::Array{Int64,1})
Closest candidates are:
  mat2vecs{T<:Integer}(::Array{T<:Integer,2}) at In[2]:2

In [4]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [5]:
m_prefs = [1 3 2 3;
               2 1 3 1;
               3 2 1 2;
               0 0 0 0]

4×4 Array{Int64,2}:
 1  3  2  3
 2  1  3  1
 3  2  1  2
 0  0  0  0

In [6]:
mat2vecs(m_prefs)

4-element Array{Array{Int64,1},1}:
 [1,2,3]
 [3,1,2]
 [2,3,1]
 [3,1,2]

In [7]:
m_prefs = [
        1 2 3 4 0;
        4 2 3 1 0;
        4 3 1 2 0;
        1 4 3 2 0;
        1 2 4 0 3
    ]

5×5 Array{Int64,2}:
 1  2  3  4  0
 4  2  3  1  0
 4  3  1  2  0
 1  4  3  2  0
 1  2  4  0  3

In [8]:
f_prefs = [
        2 3 1 4 5;
        3 1 2 4 5;
        5 4 1 2 3;
        1 4 5 2 3
    ]

4×5 Array{Int64,2}:
 2  3  1  4  5
 3  1  2  4  5
 5  4  1  2  3
 1  4  5  2  3

In [9]:
deferred_acceptance(m_prefs,f_prefs)

LoadError: UndefVarError: deferred_acceptance not defined

In [14]:
function deferred_acceptance(m_prefs::Vector{Vector{Int}},f_prefs::Vector{Vector{Int}},caps::Vector{Int})
    m = length(m_prefs)
    n = length(f_prefs)
    prop_prefs = zeros(Int,m,n+1)
    resp_prefs = zeros(Int,n,m+1)
    
    for male in 1:m
        num = length(m_prefs[male])
        for p in 1:num
            prop_prefs[male,p] = m_prefs[male][p]
        end
    end
    for fem in 1:n
        numf = length(f_prefs[fem])
        for q in 1:numf
            resp_prefs[fem,q] = f_prefs[fem][q]
        end
    end

#    prop_matches, resp_matches, indptr = deferred_acceptance(prop_prefs, resp_prefs, caps)

#    return prop_matches,resp_matches,indptr
    return prop_prefs, resp_prefs, caps
end

deferred_acceptance (generic function with 2 methods)

In [5]:
s_prefs = [3, 1, 5, 4, 0, 2,
               1, 3, 4, 2, 5, 0,
               4, 5, 3, 1, 2, 0,
               3, 4, 1, 5, 0, 2,
               1, 4, 2, 0, 3, 5,
               4, 3, 2, 1, 5, 0,
               2, 5, 1, 3, 0, 4,
               1, 3, 2, 5, 4, 0,
               4, 1, 5, 0, 2, 3,
               3, 1, 5, 2, 4, 0,
               5, 4, 1, 3, 2, 0]
    s_prefs = reshape(s_prefs, 6,11)

6×11 Array{Int64,2}:
 3  1  4  3  1  4  2  1  4  3  5
 1  3  5  4  4  3  5  3  1  1  4
 5  4  3  1  2  2  1  2  5  5  1
 4  2  1  5  0  1  3  5  0  2  3
 0  5  2  0  3  5  0  4  2  4  2
 2  0  0  2  5  0  4  0  3  0  0

In [6]:
s_prefs = mat2vecs(s_prefs)

11-element Array{Array{Int64,1},1}:
 [3,1,5,4]  
 [1,3,4,2,5]
 [4,5,3,1,2]
 [3,4,1,5]  
 [1,4,2]    
 [4,3,2,1,5]
 [2,5,1,3]  
 [1,3,2,5,4]
 [4,1,5]    
 [3,1,5,2,4]
 [5,4,1,3,2]

In [7]:
c_prefs = [3, 7, 9, 11, 5, 4, 10, 8, 6, 1,
               2, 0, 5, 7, 10, 6, 8, 2, 3, 11,
               0, 1, 4, 9, 11, 6, 8, 3, 2, 4,
               7, 1, 10, 0, 5, 9, 10, 1, 2, 11,
               4, 9, 5, 3, 6, 8, 0, 7, 2, 4,
               10, 7, 6, 1, 8, 3, 11, 9, 0, 5]
    c_prefs = reshape(c_prefs, 11+1, 5)

12×5 Array{Int64,2}:
  3   5  11  10   2
  7   7   6   1   4
  9  10   8   2  10
 11   6   3  11   7
  5   8   2   4   6
  4   2   4   9   1
 10   3   7   5   8
  8  11   1   3   3
  6   0  10   6  11
  1   1   0   8   9
  2   4   5   0   0
  0   9   9   7   5

In [8]:
c_prefs = mat2vecs(c_prefs)

5-element Array{Array{Int64,1},1}:
 [3,7,9,11,5,4,10,8,6,1,2]
 [5,7,10,6,8,2,3,11]      
 [11,6,8,3,2,4,7,1,10]    
 [10,1,2,11,4,9,5,3,6,8]  
 [2,4,10,7,6,1,8,3,11,9]  

In [11]:
caps = [4, 1, 3, 2, 1]

5-element Array{Int64,1}:
 4
 1
 3
 2
 1

In [12]:
deferred_acceptance(s_prefs, c_prefs, caps)

LoadError: MethodError: no method matching deferred_acceptance(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1}, ::Array{Int64,1})
Closest candidates are:
  deferred_acceptance(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1}) at In[4]:2

In [3]:
using MyMatchingA
using Base.Test

const _deferred_acceptance = deferred_acceptance
const test_matrix = false

function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

function sort_matches!{T<:Integer}(matches::Vector{T}, indptr::Vector{T})
    for i in 1:length(indptr)-1
        sort!(view(matches, indptr[i]:indptr[i+1]-1))
    end
end

@testset "Testing deferred acceptance" begin
    matchings_one_to_one = Array{Dict, 1}()
    matchings_many_to_one = Array{Dict, 1}()

    # Test case: one-to-one
    m, n = 4, 3
    # Males' preference orders over females [1, 2, 3] and unmatched 0
    m_prefs = [1 3 2 3;
               2 1 3 1;
               3 2 1 2;
               0 0 0 0]
    # Females' preference orders over males [1, 2, 3, 4] and unmatched 0
    f_prefs = [3 1 3;
               1 2 0;
               2 3 2;
               4 4 1;
               0 0 4]
    # Unique stable matching
    m_matches_m_opt = m_matches_f_opt = [1, 2, 3, 0]
    f_matches_m_opt = f_matches_f_opt = [1, 2, 3]
    d = Dict(
        "m_prefs" => m_prefs,
        "f_prefs" => f_prefs,
        "m_matches_m_opt" => m_matches_m_opt,
        "f_matches_m_opt" => f_matches_m_opt,
        "m_matches_f_opt" => m_matches_f_opt,
        "f_matches_f_opt" => f_matches_f_opt,
    )
    push!(matchings_one_to_one, d)

    # Test case: one-to-one; from Roth and Sotomayor Example 2.9
    m, n = 5, 4
    m_prefs = [
        1, 2, 3, 4, 0,
        4, 2, 3, 1, 0,
        4, 3, 1, 2, 0,
        1, 4, 3, 2, 0,
        1, 2, 4, 0, 3,
    ]
    m_prefs = reshape(m_prefs, n+1, m)
    f_prefs = [
        2, 3, 1, 4, 5, 0,
        3, 1, 2, 4, 5, 0,
        5, 4, 1, 2, 3, 0,
        1, 4, 5, 2, 3, 0,
    ]
    f_prefs = reshape(f_prefs, m+1, n)
    m_matches_m_opt, f_matches_m_opt = [1, 2, 3, 4, 0], [1, 2, 3, 4]
    m_matches_f_opt, f_matches_f_opt = [4, 1, 2, 3, 0], [2, 3, 4, 1]
    d = Dict(
        "m_prefs" => m_prefs,
        "f_prefs" => f_prefs,
        "m_matches_m_opt" => m_matches_m_opt,
        "f_matches_m_opt" => f_matches_m_opt,
        "m_matches_f_opt" => m_matches_f_opt,
        "f_matches_f_opt" => f_matches_f_opt,
    )
    push!(matchings_one_to_one, d)

    # Test case: one-to-one; from Roth and Sotomayor Example 2.17
    m = n = 4
    m_prefs = [
        1, 2, 3, 4, 0,
        2, 1, 4, 3, 0,
        3, 4, 1, 2, 0,
        4, 3, 2, 1, 0,
    ]
    m_prefs = reshape(m_prefs, n+1, m)
    f_prefs = [
        4, 3, 2, 1, 0,
        3, 4, 1, 2, 0,
        2, 1, 4, 3, 0,
        1, 2, 3, 4, 0,
    ]
    f_prefs = reshape(f_prefs, m+1, n)
    m_matches_m_opt = f_matches_m_opt = [1, 2, 3, 4]
    m_matches_f_opt = f_matches_f_opt = [4, 3, 2, 1]
    d = Dict(
        "m_prefs" => m_prefs,
        "f_prefs" => f_prefs,
        "m_matches_m_opt" => m_matches_m_opt,
        "f_matches_m_opt" => f_matches_m_opt,
        "m_matches_f_opt" => m_matches_f_opt,
        "f_matches_f_opt" => f_matches_f_opt,
    )
    push!(matchings_one_to_one, d)

    # Test case: many-to-one
    # From Gusfield and Irving (1989, Section 1.6.5)

    m = 11  # Number of students
    n = 5   # Number of colleges

    # Students' preference orders over colleges 1, ..., 5 and unmatched 0
    s_prefs = [3, 1, 5, 4, 0, 2,
               1, 3, 4, 2, 5, 0,
               4, 5, 3, 1, 2, 0,
               3, 4, 1, 5, 0, 2,
               1, 4, 2, 0, 3, 5,
               4, 3, 2, 1, 5, 0,
               2, 5, 1, 3, 0, 4,
               1, 3, 2, 5, 4, 0,
               4, 1, 5, 0, 2, 3,
               3, 1, 5, 2, 4, 0,
               5, 4, 1, 3, 2, 0]
    s_prefs = reshape(s_prefs, n+1, m)

    # Colleges' preference orders over students 1, ..., 11 and unmatched 0
    c_prefs = [3, 7, 9, 11, 5, 4, 10, 8, 6, 1,
               2, 0, 5, 7, 10, 6, 8, 2, 3, 11,
               0, 1, 4, 9, 11, 6, 8, 3, 2, 4,
               7, 1, 10, 0, 5, 9, 10, 1, 2, 11,
               4, 9, 5, 3, 6, 8, 0, 7, 2, 4,
               10, 7, 6, 1, 8, 3, 11, 9, 0, 5]
    c_prefs = reshape(c_prefs, m+1, n)

    # Capacities for colleges
    caps = [4, 1, 3, 2, 1]
    indptr = [1, 5, 6, 9, 11, 12]

    # Optimal stable matchings

    # Student optimal
    s_matches_s_opt = [3, 1, 4, 3, 1, 3, 2, 1, 4, 1, 5]
    c_matches_s_opt = [2, 5, 8, 10, 7, 1, 4, 6, 3, 9, 11]

    # Matching the book claims to be hospital-(or college-)optimal
    # s_matches_c_opt = [4, 4, 3, 1, 1, 3, 2, 3, 1, 5, 1]
    # c_matches_c_opt = [4, 5, 9, 11, 7, 3, 6, 8, 1, 2, 10]

    # Matching actually hospital-(or college-)optimal
    s_matches_c_opt = [4, 5, 3, 1, 1, 3, 2, 3, 1, 4, 1]
    c_matches_c_opt = [4, 5, 9, 11, 7, 3, 6, 8, 1, 10, 2]

    d = Dict(
        "s_prefs" => s_prefs,
        "c_prefs" => c_prefs,
        "caps" => caps,
        "s_matches_s_opt" => s_matches_s_opt,
        "c_matches_s_opt" => c_matches_s_opt,
        "s_matches_c_opt" => s_matches_c_opt,
        "c_matches_c_opt" => c_matches_c_opt,
        "indptr" => indptr,
    )
    push!(matchings_many_to_one, d)

    # Test case: many-to-one; from Roth and Sotomayor Page 16
    m, n = 7, 5
    s_prefs = [
        5, 1, 0, 2, 3, 4,
        2, 5, 1, 0, 3, 4,
        3, 1, 0, 2, 4, 5,
        4, 1, 0, 2, 3, 5,
        1, 2, 0, 3, 4, 5,
        1, 3, 0, 2, 4, 5,
        1, 3, 4, 0, 2, 6,
    ]
    s_prefs = reshape(s_prefs, n+1, m)
    c_prefs = [
        1, 2, 3, 4, 5, 6, 7, 0,
        5, 2, 0, 1, 3, 4, 6, 7,
        6, 7, 3, 0, 1, 2, 4, 5,
        7, 4, 0, 1, 2, 3, 5, 6,
        2, 1, 0, 3, 4, 5, 6, 7,
    ]
    c_prefs = reshape(c_prefs, m+1, n)
    caps = [3, 1, 1, 1, 1]
    indptr = [1, 4, 5, 6, 7,  8]
    s_matches_s_opt = [5, 2, 3, 4, 1, 1, 1]
    c_matches_s_opt = [5, 6, 7, 2, 3, 4, 1]
    s_matches_c_opt = [1, 5, 1, 1, 2, 3, 4]
    c_matches_c_opt = [1, 3, 4, 5, 6, 7, 2]
    d = Dict(
        "s_prefs" => s_prefs,
        "c_prefs" => c_prefs,
        "caps" => caps,
        "s_matches_s_opt" => s_matches_s_opt,
        "c_matches_s_opt" => c_matches_s_opt,
        "s_matches_c_opt" => s_matches_c_opt,
        "c_matches_c_opt" => c_matches_c_opt,
        "indptr" => indptr,
    )
    push!(matchings_many_to_one, d)

    @testset "one-to-one: Vector of Vectors" begin
        for d in matchings_one_to_one
            # Convert Matrix to Vector{Vector}
            m_prefs, f_prefs = mat2vecs.([d["m_prefs"], d["f_prefs"]])

            # Male proposal
            m_matches, f_matches = _deferred_acceptance(m_prefs, f_prefs)
            @test m_matches == d["m_matches_m_opt"]
            @test f_matches == d["f_matches_m_opt"]

            # Female proposal
            f_matches, m_matches = _deferred_acceptance(f_prefs, m_prefs)
            @test m_matches == d["m_matches_f_opt"]
            @test f_matches == d["f_matches_f_opt"]
        end
    end

    @testset "many-to-one: Vector of Vectors" begin
        for d in matchings_many_to_one
            s_prefs, c_prefs = mat2vecs.([d["s_prefs"], d["c_prefs"]])

            # Default (Student proposal)
            s_matches, c_matches, indptr =
                _deferred_acceptance(s_prefs, c_prefs, d["caps"])
            sort_matches!(c_matches, indptr)
            @test s_matches == d["s_matches_s_opt"]
            @test c_matches == d["c_matches_s_opt"]
            @test indptr == d["indptr"]
        end
    end

    if test_matrix
        @testset "one-to-one: Matrix" begin
            for d in matchings_one_to_one
                m_prefs, f_prefs = d["m_prefs"], d["f_prefs"]

                # Male proposal
                m_matches, f_matches = _deferred_acceptance(m_prefs, f_prefs)
                @test m_matches == d["m_matches_m_opt"]
                @test f_matches == d["f_matches_m_opt"]

                # Female proposal
                f_matches, m_matches = _deferred_acceptance(f_prefs, m_prefs)
                @test m_matches == d["m_matches_f_opt"]
                @test f_matches == d["f_matches_f_opt"]
            end
        end

        @testset "many-to-one: Matrix" begin
            for d in matchings_many_to_one
                s_prefs, c_prefs = d["s_prefs"], d["c_prefs"]

                # Default (Student proposal)
                s_matches, c_matches, indptr =
                    _deferred_acceptance(s_prefs, c_prefs, d["caps"])
                sort_matches!(c_matches, indptr)
                @test s_matches == d["s_matches_s_opt"]
                @test c_matches == d["c_matches_s_opt"]
                @test indptr == d["indptr"]
            end
        end
    end
end

one-to-one: Vector of Vectors: Error During Test
  Got an exception of type MethodError outside of a @test


  MethodError: no method matching deferred_acceptance(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1})
   in macro expansion; at ./In[3]:207 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro expansion; at ./In[3]:201 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in anonymous at ./<missing>:?
   in include_string(::String, ::String) at ./loading.jl:441
   in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/sasakiakihiro/.julia/v0.5/IJulia/src/execute_request.jl:156
   in eventloop(::ZMQ.Socket) at /Users/sasakiakihiro/.julia/v0.5/IJulia/src/eventloop.jl:8
   in (::IJulia.##13#19)() at ./task.jl:360
many-to-one: Vector of Vectors: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching deferred_acceptance(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1}, ::Array{Int64,1})
   in macro expansion; at ./In[3]:223 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro ex

LoadError: Some tests did not pass: 0 passed, 0 failed, 2 errored, 0 broken.

In [14]:
function deferred_acceptance(m_prefs::Vector{Vector{Int}},f_prefs::Vector{Vector{Int}})
    m = length(m_prefs)
    n = length(f_prefs)
    prop_prefs = zeros(Int,m,n+1)
    resp_prefs = zeros(Int,n,m+1)
    
    for male in 1:m
        num = length(m_prefs[male])
        for p in 1:num
            prop_prefs[male,p] = m_prefs[male][p]
        end
    end
    for fem in 1:n
        numf = length(f_prefs[fem])
        for q in 1:numf
            resp_prefs[fem,q] = f_prefs[fem][q]
        end
    end
    
    caps = ones(Int, size(resp_prefs, 1))
#    prop_matches, resp_matches, indptr =
#        deferred_acceptance(prop_prefs, resp_prefs, caps)
#    return prop_matches, resp_matches
    return prop_prefs, resp_prefs,caps
end

deferred_acceptance (generic function with 2 methods)

In [16]:
typeof(deferred_acceptance(s_prefs, c_prefs))

Tuple{Array{Int64,2},Array{Int64,2},Array{Int64,1}}