In [1]:
Pkg.checkout("MyMatchingA")

INFO: Checking out MyMatchingA master...
INFO: Pulling MyMatchingA latest master...
INFO: No packages to install, update or remove


In [6]:
Pkg.test("MyMatchingA")

INFO: Testing MyMatchingA


one-to-one: Vector of Vectors: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching deferred_acceptanceA(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1})
   in macro expansion; at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runtests.jl:207 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro expansion; at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runtests.jl:201 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:488
   in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
   in process_options(::Base.JLOptions) at ./client.jl:265
   in _start() at ./client.jl:321
   in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
many-to-one: Vector of Vectors: Error During Test
  Got an exception of type MethodError outs

ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 2 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:498
 in macro expansion; at ./test.jl:681 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runtests.jl, in expression starting on line 17
=============================[ ERROR: MyMatchingA ]=============================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --col

LoadError: MyMatchingA had test errors

In [2]:
using MyMatchingA

In [11]:
prop_prefs = [3  1  3  1;
              1  2  2  2;
              2  3  1  3;
              0  0  0  0]

4×4 Array{Int64,2}:
 3  1  3  1
 1  2  2  2
 2  3  1  3
 0  0  0  0

In [12]:
transpose(prop_prefs)

4×4 Array{Int64,2}:
 3  1  2  0
 1  2  3  0
 3  2  1  0
 1  2  3  0

In [3]:
prop_prefs=Array{Int}[[3,1,2,0],[1,2,3,0],[3,2,1,0],[1,2,3,0]]

4-element Array{Array{Int64,N},1}:
 [3,1,2,0]
 [1,2,3,0]
 [3,2,1,0]
 [1,2,3,0]

In [3]:
prop_prefs = [3 1 2 ;
              1 2 3 ;
              3 2 1 ;
              1 2 3 ]

4×3 Array{Int64,2}:
 3  1  2
 1  2  3
 3  2  1
 1  2  3

In [5]:
resp_prefs = [4  4  4;
              1  1  2;
              3  2  1;
              2  3  3;
              0  0  0]

5×3 Array{Int64,2}:
 4  4  4
 1  1  2
 3  2  1
 2  3  3
 0  0  0

In [12]:
resp_prefs = Array{Int}[[4,1,3,2,0],[4,1,2,3,0],[4,2,1,3,0]]

3-element Array{Array{Int64,N},1}:
 [4,1,3,2,0]
 [4,1,2,3,0]
 [4,2,1,3,0]

In [4]:
resp_prefs = [4 1 3 2 ;
              4 1 2 3 ;
              4 2 1 3 ]

3×4 Array{Int64,2}:
 4  1  3  2
 4  1  2  3
 4  2  1  3

In [9]:
size(resp_prefs, 1)

3

In [5]:
caps = [2,3,2]

3-element Array{Int64,1}:
 2
 3
 2

In [15]:
typeof(prop_prefs)

Array{Int64,2}

In [16]:
typeof(resp_prefs)

Array{Int64,2}

In [17]:
typeof(caps)

Array{Int64,1}

In [6]:
deferred_acceptanceA(prop_prefs,resp_prefs,caps)

b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 4
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 1
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 3
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 2
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 4
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 1
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 2
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 3
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 4
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 2
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 1
b = length(resp_prefs[j,:]) = 4
a = resp_prefs[j,i] = 3
q = resp_rankings = [2 2 3; 4 3 2; 3 4 4; 1 1 1]
i = get_single(prop_matches) = 1
j = (prop_prefs[i])[prop_next_to_propose[i]] = 3
p = resp_matches[indptr[j]:indptr[j + 1] - 1] = [0,0]
a = findfirst(p,0) = 1
i = get_single(prop_matches) = 2
j = (prop_prefs[i])[prop_next_to_propose[i]] = 1
p = resp_matches[indptr[j]:indptr[j + 

([3,1,3,1],[2,4,0,0,0,1,3],[1,3,6,8])

In [35]:
list_comp = Array(Int, 3)

3-element Array{Int64,1}:
 4638988464
 4577296608
 4577296672

In [36]:
typeof(findfirst(caps,2))

Int64

In [37]:
using Matching

In [38]:
deferred_acceptance(prop_prefs,resp_prefs,caps)

LoadError: MethodError: no method matching deferred_acceptance(::Array{Array{Int64,N},1}, ::Array{Int64,2}, ::Array{Int64,1})
Closest candidates are:
  deferred_acceptance(::Array{Int64,2}, ::Array{Int64,2}, ::Array{Int64,1}) at /Users/sasakiakihiro/.julia/v0.5/Matching/src/deferred_acceptance.jl:233
  deferred_acceptance(::Array{Int64,2}, ::Array{Int64,2}, ::Array{Int64,1}, ::Array{Int64,1}) at /Users/sasakiakihiro/.julia/v0.5/Matching/src/deferred_acceptance.jl:49
  deferred_acceptance{P<:Matching.DAProposal}(::Array{Int64,2}, ::Array{Int64,2}, ::Array{Int64,1}, ::Type{P<:Matching.DAProposal}) at /Users/sasakiakihiro/.julia/v0.5/Matching/src/deferred_acceptance.jl:233
  ...

In [39]:
typeof(size(prop_prefs, 2))

Int64

In [40]:
size(resp_prefs, 2)

3

In [41]:
m = size(prop_prefs, 2)
    n = size(resp_prefs, 2)

3

In [42]:
prop_matches = fill(-1, m)

1-element Array{Int64,1}:
 -1

In [43]:
prop_next_to_propose = ones(Int64, m)

1-element Array{Int64,1}:
 1

In [44]:
L = sum(caps)
    resp_matches = zeros(Int64, L)

7-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0

In [45]:
indptr = Array(Int,n+1)
indptr[1] = 1
    for i in 1:n
        indptr[i+1] = indptr[i] + caps[i]
    end  

In [46]:
typeof(indptr)

Array{Int64,1}

In [48]:
resp_rankings = (m+1)*ones(Int, m, n)    
    
    for j in 1:n
       for i in 1:length(resp_prefs[j])
           b = length(resp_prefs[j])
           a = resp_prefs[j][i]
           resp_rankings[a,j] = i
       end
    end

LoadError: BoundsError: attempt to access 1×3 Array{Int64,2} at index [4,1]

In [49]:
typeof(resp_rankings)

Array{Int64,2}

In [50]:
resp_rankings

1×3 Array{Int64,2}:
 2  2  2

In [8]:
s_prefs = [
        5, 1, 0, 2, 3, 4,
        2, 5, 1, 0, 3, 4,
        3, 1, 0, 2, 4, 5,
        4, 1, 0, 2, 3, 5,
        1, 2, 0, 3, 4, 5,
        1, 3, 0, 2, 4, 5,
        1, 3, 4, 0, 2, 6,
    ]

42-element Array{Int64,1}:
 5
 1
 0
 2
 3
 4
 2
 5
 1
 0
 3
 4
 3
 ⋮
 1
 3
 0
 2
 4
 5
 1
 3
 4
 0
 2
 6

In [9]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [10]:
mat2vecs(s_prefs)

LoadError: MethodError: no method matching mat2vecs(::Array{Int64,1})
Closest candidates are:
  mat2vecs{T<:Integer}(::Array{T<:Integer,2}) at In[9]:2

In [3]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [6]:
m_prefs = [1 3 2 3;
               2 1 3 1;
               3 2 1 2;
               0 0 0 0]

4×4 Array{Int64,2}:
 1  3  2  3
 2  1  3  1
 3  2  1  2
 0  0  0  0

In [7]:
mat2vecs(m_prefs)

4-element Array{Array{Int64,1},1}:
 [1,2,3]
 [3,1,2]
 [2,3,1]
 [3,1,2]

In [3]:
m_prefs = [
        1 2 3 4 0;
        4 2 3 1 0;
        4 3 1 2 0;
        1 4 3 2 0;
        1 2 4 0 3
    ]

5×5 Array{Int64,2}:
 1  2  3  4  0
 4  2  3  1  0
 4  3  1  2  0
 1  4  3  2  0
 1  2  4  0  3

In [4]:
f_prefs = [
        2 3 1 4 5;
        3 1 2 4 5;
        5 4 1 2 3;
        1 4 5 2 3
    ]

4×5 Array{Int64,2}:
 2  3  1  4  5
 3  1  2  4  5
 5  4  1  2  3
 1  4  5  2  3

In [5]:
deferred_acceptanceB(m_prefs,f_prefs)

q = resp_rankings = [3 2 3 1; 1 3 4 4; 2 1 5 5; 4 4 2 2; 5 5 1 3]
i = get_single(prop_matches) = 1
j = (prop_prefs[i])[prop_next_to_propose[i]] = 1
p = resp_matches[indptr[j]:indptr[j + 1] - 1] = [0]
a = findfirst(p,0) = 1
prop_next_to_propose[i] += 1 = 2
i = get_single(prop_matches) = 2
j = (prop_prefs[i])[prop_next_to_propose[i]] = 4
p = resp_matches[indptr[j]:indptr[j + 1] - 1] = [0]
a = findfirst(p,0) = 1
prop_next_to_propose[i] += 1 = 2
i = get_single(prop_matches) = 3
j = (prop_prefs[i])[prop_next_to_propose[i]] = 4
p = resp_matches[indptr[j]:indptr[j + 1] - 1] = [2]
a = findfirst(p,0) = 0
prop_next_to_propose[i] += 1 = 2
i = get_single(prop_matches) = 3
i = get_single(prop_matches) = 4
j = (prop_prefs[i])[prop_next_to_propose[i]] = 1
p = resp_matches[indptr[j]:indptr[j + 1] - 1] = [1]
a = findfirst(p,0) = 0
prop_next_to_propose[i] += 1 = 2
i = get_single(prop_matches) = 4
i = get_single(prop_matches) = 5
j = (prop_prefs[i])[prop_next_to_propose[i]] = 1
p = resp_matches[indptr[j]

([1,4,0,0,0],[1,0,0,2])