In [1]:
Pkg.checkout("MyMatchingA")

INFO: Checking out MyMatchingA master...
INFO: Pulling MyMatchingA latest master...
INFO: No packages to install, update or remove


In [2]:
Pkg.test("MyMatchingA")

INFO: Testing MyMatchingA


one-to-one: Vector of Vectors: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching deferred_acceptance(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1})
   in macro expansion; at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runtests.jl:207 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro expansion; at /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runtests.jl:201 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:488
   in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
   in process_options(::Base.JLOptions) at ./client.jl:265
   in _start() at ./client.jl:321
   in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
many-to-one: Vector of Vectors: Error During Test
  Got an exception of type MethodError outsi

ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 2 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:498
 in macro expansion; at ./test.jl:681 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/sasakiakihiro/.julia/v0.5/MyMatchingA/test/runtests.jl, in expression starting on line 17
=============================[ ERROR: MyMatchingA ]=============================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --col

LoadError: MyMatchingA had test errors

In [27]:
using MyMatchingA

In [11]:
prop_prefs = [3  1  3  1;
              1  2  2  2;
              2  3  1  3;
              0  0  0  0]

4×4 Array{Int64,2}:
 3  1  3  1
 1  2  2  2
 2  3  1  3
 0  0  0  0

In [12]:
transpose(prop_prefs)

4×4 Array{Int64,2}:
 3  1  2  0
 1  2  3  0
 3  2  1  0
 1  2  3  0

In [3]:
prop_prefs=Array{Int}[[3,1,2,0],[1,2,3,0],[3,2,1,0],[1,2,3,0]]

4-element Array{Array{Int64,N},1}:
 [3,1,2,0]
 [1,2,3,0]
 [3,2,1,0]
 [1,2,3,0]

In [3]:
prop_prefs = [3 1 2 ;
              1 2 3 ;
              3 2 1 ;
              1 2 3 ]

4×3 Array{Int64,2}:
 3  1  2
 1  2  3
 3  2  1
 1  2  3

In [5]:
resp_prefs = [4  4  4;
              1  1  2;
              3  2  1;
              2  3  3;
              0  0  0]

5×3 Array{Int64,2}:
 4  4  4
 1  1  2
 3  2  1
 2  3  3
 0  0  0

In [12]:
resp_prefs = Array{Int}[[4,1,3,2,0],[4,1,2,3,0],[4,2,1,3,0]]

3-element Array{Array{Int64,N},1}:
 [4,1,3,2,0]
 [4,1,2,3,0]
 [4,2,1,3,0]

In [4]:
resp_prefs = [4 1 3 2 ;
              4 1 2 3 ;
              4 2 1 3 ]

3×4 Array{Int64,2}:
 4  1  3  2
 4  1  2  3
 4  2  1  3

In [9]:
size(resp_prefs, 1)

3

In [5]:
caps = [2,3,2]

3-element Array{Int64,1}:
 2
 3
 2

In [1]:
s_prefs = [
        5, 1, 0, 2, 3, 4,
        2, 5, 1, 0, 3, 4,
        3, 1, 0, 2, 4, 5,
        4, 1, 0, 2, 3, 5,
        1, 2, 0, 3, 4, 5,
        1, 3, 0, 2, 4, 5,
        1, 3, 4, 0, 2, 6,
    ]

42-element Array{Int64,1}:
 5
 1
 0
 2
 3
 4
 2
 5
 1
 0
 3
 4
 3
 ⋮
 1
 3
 0
 2
 4
 5
 1
 3
 4
 0
 2
 6

In [2]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [3]:
mat2vecs(s_prefs)

LoadError: MethodError: no method matching mat2vecs(::Array{Int64,1})
Closest candidates are:
  mat2vecs{T<:Integer}(::Array{T<:Integer,2}) at In[2]:2

In [4]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [5]:
m_prefs = [1 3 2 3;
               2 1 3 1;
               3 2 1 2;
               0 0 0 0]

4×4 Array{Int64,2}:
 1  3  2  3
 2  1  3  1
 3  2  1  2
 0  0  0  0

In [6]:
mat2vecs(m_prefs)

4-element Array{Array{Int64,1},1}:
 [1,2,3]
 [3,1,2]
 [2,3,1]
 [3,1,2]

In [7]:
m_prefs = [
        1 2 3 4 0;
        4 2 3 1 0;
        4 3 1 2 0;
        1 4 3 2 0;
        1 2 4 0 3
    ]

5×5 Array{Int64,2}:
 1  2  3  4  0
 4  2  3  1  0
 4  3  1  2  0
 1  4  3  2  0
 1  2  4  0  3

In [8]:
f_prefs = [
        2 3 1 4 5;
        3 1 2 4 5;
        5 4 1 2 3;
        1 4 5 2 3
    ]

4×5 Array{Int64,2}:
 2  3  1  4  5
 3  1  2  4  5
 5  4  1  2  3
 1  4  5  2  3

In [9]:
deferred_acceptance(m_prefs,f_prefs)

LoadError: UndefVarError: deferred_acceptance not defined

In [52]:
function deferred_acceptance(m_prefs::Vector{Vector{Int}},f_prefs::Vector{Vector{Int}},caps::Vector{Int})
    m = length(m_prefs)
    n = length(f_prefs)
    prop_prefs = zeros(Int,m,n+1)
    resp_prefs = zeros(Int,n,m+1)
    
    for male in 1:m
        num = length(m_prefs[male])
        for p in 1:num
            prop_prefs[male,p] = m_prefs[male][p]
        end
    end
    for fem in 1:n
        numf = length(f_prefs[fem])
        for q in 1:numf
            resp_prefs[fem,q] = f_prefs[fem][q]
        end
    end

    prop_matches, resp_matches, indptr = deferred_acceptance(prop_prefs, resp_prefs, caps)

    return prop_matches,resp_matches,indptr
#    return prop_prefs
end

deferred_acceptance (generic function with 3 methods)

In [54]:
s_prefs = [3, 1, 5, 4, 0, 2,
               1, 3, 4, 2, 5, 0,
               4, 5, 3, 1, 2, 0,
               3, 4, 1, 5, 0, 2,
               1, 4, 2, 0, 3, 5,
               4, 3, 2, 1, 5, 0,
               2, 5, 1, 3, 0, 4,
               1, 3, 2, 5, 4, 0,
               4, 1, 5, 0, 2, 3,
               3, 1, 5, 2, 4, 0,
               5, 4, 1, 3, 2, 0]
    s_prefs = reshape(s_prefs, 6,11)

6×11 Array{Int64,2}:
 3  1  4  3  1  4  2  1  4  3  5
 1  3  5  4  4  3  5  3  1  1  4
 5  4  3  1  2  2  1  2  5  5  1
 4  2  1  5  0  1  3  5  0  2  3
 0  5  2  0  3  5  0  4  2  4  2
 2  0  0  2  5  0  4  0  3  0  0

In [55]:
s_prefs = mat2vecs(s_prefs)

11-element Array{Array{Int64,1},1}:
 [3,1,5,4]  
 [1,3,4,2,5]
 [4,5,3,1,2]
 [3,4,1,5]  
 [1,4,2]    
 [4,3,2,1,5]
 [2,5,1,3]  
 [1,3,2,5,4]
 [4,1,5]    
 [3,1,5,2,4]
 [5,4,1,3,2]

In [57]:
c_prefs = [3, 7, 9, 11, 5, 4, 10, 8, 6, 1,
               2, 0, 5, 7, 10, 6, 8, 2, 3, 11,
               0, 1, 4, 9, 11, 6, 8, 3, 2, 4,
               7, 1, 10, 0, 5, 9, 10, 1, 2, 11,
               4, 9, 5, 3, 6, 8, 0, 7, 2, 4,
               10, 7, 6, 1, 8, 3, 11, 9, 0, 5]
    c_prefs = reshape(c_prefs, 11+1, 5)

12×5 Array{Int64,2}:
  3   5  11  10   2
  7   7   6   1   4
  9  10   8   2  10
 11   6   3  11   7
  5   8   2   4   6
  4   2   4   9   1
 10   3   7   5   8
  8  11   1   3   3
  6   0  10   6  11
  1   1   0   8   9
  2   4   5   0   0
  0   9   9   7   5

In [58]:
c_prefs = mat2vecs(c_prefs)

5-element Array{Array{Int64,1},1}:
 [3,7,9,11,5,4,10,8,6,1,2]
 [5,7,10,6,8,2,3,11]      
 [11,6,8,3,2,4,7,1,10]    
 [10,1,2,11,4,9,5,3,6,8]  
 [2,4,10,7,6,1,8,3,11,9]  

In [59]:
caps = [4, 1, 3, 2, 1]

5-element Array{Int64,1}:
 4
 1
 3
 2
 1

In [60]:
deferred_acceptance(s_prefs, c_prefs, caps)

LoadError: MethodError: no method matching deferred_acceptance(::Array{Int64,2}, ::Array{Int64,2}, ::Array{Int64,1})
Closest candidates are:
  deferred_acceptance(::Array{Int64,2}, ::Array{Int64,2}) at In[17]:157
  deferred_acceptance(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1}, ::Array{Int64,1}) at In[52]:2

In [46]:
transpose(s_prefs)

1×11 Array{Array{Int64,2},2}:
 [3 1 5 4]  [1 3 … 2 5]  [4 5 … 1 2]  …  [4 1 5]  [3 1 … 2 4]  [5 4 … 3 2]

In [43]:
function deferred_acceptance(m_prefs::Vector{Vector{Int}},
                             f_prefs::Vector{Vector{Int}})
    # m_prefs と f_prefs をそれぞれ2次元配列 (たとえば m_prefs_2d と f_prefs_2d) に
    # 変換する
    return deferred_acceptance(m_prefs_2d, f_prefs_2d)
end

deferred_acceptance (generic function with 3 methods)